
alter session set"_ORACLE_SCRIPT"=TRUE;

CREATE USER BDY1102_P3 IDENTIFIED BY "BDY1102_P3.practica_3"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P3 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P3;
GRANT "RESOURCE" TO BDY1102_P3;
ALTER USER BDY1102_P3 DEFAULT ROLE "RESOURCE";


/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_P3 IDENTIFIED BY "BDY1102_P3.practica_3"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P3 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P3;
GRANT "RESOURCE" TO BDY1102_P3;
ALTER USER BDY1102_P3 DEFAULT ROLE "RESOURCE";