/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER  BDY1102_P4 IDENTIFIED BY "BDY1102_P4.practica_4"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P4 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P4;
GRANT "RESOURCE" TO BDY1102_P4;
ALTER USER BDY1102_P4 DEFAULT ROLE "RESOURCE";


/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_P4 IDENTIFIED BY "BDY1102_P4.practica_4"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P4 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P4;
GRANT "RESOURCE" TO BDY1102_P4;
ALTER USER BDY1102_P4 DEFAULT ROLE "RESOURCE";