/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER BDY1102_P2 IDENTIFIED BY "BDY1102_P2.practica_2"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P2;
GRANT "RESOURCE" TO BDY1102_P2;
ALTER USER BDY1102_P2 DEFAULT ROLE "RESOURCE";


/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_P2 IDENTIFIED BY "BDY1102_P2.practica_2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P2 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P2;
GRANT "RESOURCE" TO BDY1102_P2;
ALTER USER BDY1102_P2 DEFAULT ROLE "RESOURCE";