--CREACION DE USUARIO CON SYS EN LOCALHOST
CREATE USER  BDY1102_EP1 IDENTIFIED BY "BDY1102_EP1"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_EP1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_EP1;
GRANT "RESOURCE" TO BDY1102_EP1;
ALTER USER BDY1102_EP1 DEFAULT ROLE "RESOURCE";
