--=======================================================================================================================================================
--DROPEO DE TABLAS
--=======================================================================================================================================================

DROP TABLE ASIGNAR CASCADE CONSTRAINTS;
DROP TABLE CAMION CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE EMPRESA_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE GUARDIA CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE RECINTO CASCADE CONSTRAINTS;
DROP TABLE TRACTO_CAMION CASCADE CONSTRAINTS;
DROP TABLE TURNO CASCADE CONSTRAINTS;
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS;


DROP SEQUENCE ID_TURNO;
DROP SEQUENCE ID_GUARDIA;
DROP SEQUENCE ID_CIUDAD;
DROP SEQUENCE ID_COMUNA;
DROP SEQUENCE ID_PAIS;
DROP SEQUENCE ID_EMPRESA_CLIENTE;
DROP SEQUENCE ID_RECINTO;


--=======================================================================================================================================================
--CREACIÓN DE TABLAS
--=======================================================================================================================================================


CREATE TABLE asignar (
    id_guardia   NUMBER NOT NULL,
    id_turno     NUMBER NOT NULL
);

ALTER TABLE asignar ADD CONSTRAINT asignar_pk PRIMARY KEY ( id_guardia,
                                                            id_turno );

CREATE TABLE camion (
    patente_camion          VARCHAR2(7) NOT NULL,
    marca_camion            VARCHAR2(50) NOT NULL,
    modelo_camion           VARCHAR2(50),
    cantidad_ejes_camion    NUMBER NOT NULL,
    empresa_camion         VARCHAR2(50) NOT NULL,
    id_guardia              NUMBER NOT NULL,
    run_conductor           NUMBER NOT NULL
);

ALTER TABLE camion ADD CONSTRAINT camion_pk PRIMARY KEY ( patente_camion );

CREATE TABLE ciudad (
    id_ciudad     NUMBER NOT NULL,
    nombre_ciudad VARCHAR2(50) NOT NULL,
    id_pais       NUMBER NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY ( id_ciudad );

CREATE TABLE comuna (
    id_comuna        NUMBER NOT NULL,
    nombre_comuna    VARCHAR2(50) NOT NULL,
    id_ciudad NUMBER NOT NULL
);

ALTER TABLE comuna ADD CONSTRAINT comuna_pk PRIMARY KEY ( id_comuna );

CREATE TABLE conductor (
    run_conductor       NUMBER NOT NULL,
    dvrun_conductor     VARCHAR2(1),
    pnombre_conductor   VARCHAR2(30) NOT NULL,
    snombre_conductor   VARCHAR2(30),
    appaterno_conductor VARCHAR2(30),
    fecha_nac_conductor DATE,
    direccion_conductor VARCHAR2(100) NOT NULL,
    fono_conductor      NUMBER NOT NULL,
    id_guardia          NUMBER NOT NULL
);

ALTER TABLE conductor ADD CONSTRAINT conductor_pk PRIMARY KEY ( run_conductor );

CREATE TABLE empresa_cliente (
    id_empresa     NUMBER NOT NULL,
    nombre_empresa VARCHAR2(100) NOT NULL
);

ALTER TABLE empresa_cliente ADD CONSTRAINT empresa_cliente_pk PRIMARY KEY ( id_empresa );

CREATE TABLE guardia (
    id_guardia             NUMBER NOT NULL,
    pnombre_guardia       VARCHAR2(20) NOT NULL,
    snombre_guardia       VARCHAR2(20),
    appaterno_guardia      VARCHAR2(20) NOT NULL,
    apmaterno_guardia     VARCHAR2(20),
    fecha_nac_guardia      DATE NOT NULL,
    os10_guardia           VARCHAR2(50) NOT NULL,
    fecha_contrato_guardia DATE NOT NULL,
    correo_guardia         VARCHAR2(100),
    fono_guardia           NUMBER,
    id_recinto             NUMBER NOT NULL,
    direccion_guardia      VARCHAR2(100) NOT NULL,
    id_comuna              NUMBER NOT NULL
);

ALTER TABLE guardia ADD CONSTRAINT guardia_pk PRIMARY KEY ( id_guardia );

CREATE TABLE pais (
    id_pais     NUMBER NOT NULL,
    nombre_pais VARCHAR2(50) NOT NULL
);

ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY ( id_pais );

CREATE TABLE recinto (
    id_recinto                 NUMBER NOT NULL,
    nombre_recinto             VARCHAR2(50) NOT NULL,
    direccion_recinto          VARCHAR2(100) NOT NULL,
    id_empresa                 NUMBER NOT NULL,
    id_comuna                  NUMBER
);

ALTER TABLE recinto ADD CONSTRAINT recinto_pk PRIMARY KEY ( id_recinto );

CREATE TABLE tracto_camion (
    patente_tracto_camion       VARCHAR2(7) NOT NULL,
    marca_tracto_camion         VARCHAR2(50) NOT NULL,
    modelo_tracto_camion        VARCHAR2(50),
    cantidad_ejes_tracto_camion NUMBER NOT NULL,
    patente_camion              VARCHAR2(7) NOT NULL
);

ALTER TABLE tracto_camion ADD CONSTRAINT tracto_camion_pk PRIMARY KEY ( patente_tracto_camion );

CREATE TABLE turno (
    id_turno        NUMBER NOT NULL,
    fecha_ini_turno DATE NOT NULL,
    fecha_ter_turno DATE NOT NULL,
    horario_turno   VARCHAR2(20) NOT NULL,
    valor_turno     NUMBER
);

ALTER TABLE turno ADD CONSTRAINT turno_pk PRIMARY KEY ( id_turno );

ALTER TABLE asignar
    ADD CONSTRAINT asignar_guardia_fk FOREIGN KEY ( id_guardia )
        REFERENCES guardia ( id_guardia );

ALTER TABLE asignar
    ADD CONSTRAINT asignar_turno_fk FOREIGN KEY ( id_turno )
        REFERENCES turno ( id_turno );

ALTER TABLE camion
    ADD CONSTRAINT camion_conductor_fk FOREIGN KEY ( run_conductor )
        REFERENCES conductor ( run_conductor );

ALTER TABLE camion
    ADD CONSTRAINT camion_guardia_fk FOREIGN KEY ( id_guardia )
        REFERENCES guardia ( id_guardia );

ALTER TABLE ciudad
    ADD CONSTRAINT ciudad_pais_fk FOREIGN KEY ( id_pais )
        REFERENCES pais ( id_pais );

ALTER TABLE comuna
    ADD CONSTRAINT comuna_ciudad_fk FOREIGN KEY ( id_ciudad )
        REFERENCES ciudad ( id_ciudad );

ALTER TABLE conductor
    ADD CONSTRAINT conductor_guardia_fk FOREIGN KEY ( id_guardia )
        REFERENCES guardia ( id_guardia );

ALTER TABLE guardia
    ADD CONSTRAINT guardia_comuna_fk FOREIGN KEY ( id_comuna )
        REFERENCES comuna ( id_comuna );

ALTER TABLE guardia
    ADD CONSTRAINT guardia_recinto_fk FOREIGN KEY ( id_recinto )
        REFERENCES recinto ( id_recinto );

ALTER TABLE recinto
    ADD CONSTRAINT recinto_comuna_fk FOREIGN KEY ( id_comuna )
        REFERENCES comuna ( id_comuna );

ALTER TABLE recinto
    ADD CONSTRAINT recinto_empresa_cliente_fk FOREIGN KEY ( id_empresa )
        REFERENCES empresa_cliente ( id_empresa );

ALTER TABLE tracto_camion
    ADD CONSTRAINT tracto_camion_camion_fk FOREIGN KEY ( patente_camion )
        REFERENCES camion ( patente_camion );

        
--==============================================================================
--CREACION DE SECUENCIAS AUTOINCREMENTABLES
--==============================================================================
CREATE SEQUENCE ID_TURNO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_GUARDIA START WITH 10 INCREMENT BY 20;
CREATE SEQUENCE ID_CIUDAD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_COMUNA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_PAIS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_EMPRESA_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_RECINTO START WITH 1 INCREMENT BY 1;

--==============================================================================
--INSERCION DE DATOS
--==============================================================================
INSERT INTO EMPRESA_CLIENTE VALUES(ID_EMPRESA_CLIENTE.NEXTVAL,'TNT LIT CARGO ZONA NORTE');
INSERT INTO EMPRESA_CLIENTE VALUES(ID_EMPRESA_CLIENTE.NEXTVAL,'TNT LIT CARGO ZONA CENTRAL');
INSERT INTO EMPRESA_CLIENTE VALUES(ID_EMPRESA_CLIENTE.NEXTVAL,'TNT LIT CARGO ZONA SUR');
INSERT INTO EMPRESA_CLIENTE VALUES(ID_EMPRESA_CLIENTE.NEXTVAL,'TNT LIT CARGO ZONA AUSTRAL');
INSERT INTO EMPRESA_CLIENTE VALUES(ID_EMPRESA_CLIENTE.NEXTVAL,'TNT LIT CARGO ZONA RM');

INSERT INTO PAIS VALUES (ID_PAIS.NEXTVAL,'CHILE');

INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ALERCE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ALGARROBO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ALTO HOSPICIO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ALTO JAHUEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ANCUD',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ANDACOLLO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ANGOL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ANTOFAGASTA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ARAUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ARICA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'BATUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'BOLLENAR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'BUIN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'BULNES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CABILDO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CABRERO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CALAMA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CALBUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CALDERA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CALERA DE TANGO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CALLE LARGA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CAÑETE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CARAHUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CARTAGENA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CASABLANCA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CASTRO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CATEMU',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CAUQUENES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CERRILLOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CERRO NAVIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHAITEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHAMISERO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHAÑARAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHEPICA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHICUREO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHIGUAYANTE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHILE CHICO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHILLAN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHILLAN VIEJO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHIMBARONGO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CHONCHI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CIUDAD DEL VALLE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COCHRANE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CODEGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COELEMU',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COIHUECO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COLBUN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COLLIPULLI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COLTAUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COMBARBALA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CONCEPCION',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CONCHALI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CONCON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CONSTITUCION',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COPIAPO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COQUIMBO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CORONEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'COYHAIQUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CULENAR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CUNCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CURACAUTIN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CURACAVI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CURANILAHUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'CURICO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'DALCAHUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'DIEGO DE ALMAGRO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'DONIÑUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL BOSQUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL MELON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL MONTE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL PALQUI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL PRINCIPAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL QUISCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL SALVADOR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'EL TABO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ESTACION CENTRAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'FREIRE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'FRESIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'FRUTILLAR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'FUTRONO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'GORBEA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'GRANEROS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'GULTRO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HANGA ROA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HIJUELAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUALAÑE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUALPEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUALQUI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUASCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUECHURABA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'HUEPIL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ILLAPEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'INDEPENDENCIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'IQUIQUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ISLA DE MAIPO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA CALERA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA CISTERNA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA CRUZ',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA FLORIDA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA GRANJA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA ISLITA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA LAJA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA LIGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA PINTANA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA PUNTA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA REINA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA SERENA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LA UNION',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LABRANZA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAMPA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LANCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LARAQUETE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAS CABRAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAS CONDES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAS CRUCES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAS VENTANAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LAUTARO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LEBU',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LIMACHE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LINARES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LLAILLAY',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LLANQUIHUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LO BARNECHE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LO ESPEJO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LO MIRANDA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LO PRADO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LONCOCHE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LONGAVI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS ALAMOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS ANDES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS ANGELES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS LAGOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS MUERMOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOS VILOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'LOTA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MACHALI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MACUL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MAIPU',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MAULE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MEJILLONES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MELIPILLA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MOLINA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MONTE AGUILA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MONTE PATRIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'MULCHEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ÑUÑOA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'NACIMIENTO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'NANCAGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'NOGALES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'NUEVA IMPERIAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'OLMUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'OSORNO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'OVALLE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PADRE DE LAS CASAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PAILLACO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PAINE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PANGUIPULLI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PARRAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PEDRO AGUIRRE CERDA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PEÑAFLOR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PENCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PERALILLO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PEUMO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PICHIDEGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PICHILEMU',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PITRUFQUEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PLACILLA DE PEÑUELAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PORVENIR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'POZO ALMONTE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PROVIDENCIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUCHUNCAVI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUCON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUDAHUEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUENTE ALTO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUERTO AYSEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUERTO MONTT',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUERTO NATALES',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUERTO VARAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUERTO WILLIAMS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUNITAQUI',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUNTA ARENAS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUREN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PURRANQUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUTAENDO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'PUTRE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUELLON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUILICURA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUILLON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUILLOTA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUILPUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUINTA DE TILTOCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUINTA NORMAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUINTERO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'QUIRIGUE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RANCAGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RANCAGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RAUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RECOLETA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RENAICO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RENGO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'REQUINOA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RETIRO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RINCONADA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RIO BUENO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'RIO NEGRO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'ROMERAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SALAMANCA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN ANTONIO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN BERNARDO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN CARLOS',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN CLEMENTE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN FELIPE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN ESTEBAN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN FERNANDO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN FRANCISCO DE MOSTAZAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN JAVIER',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN JOAQUIN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN JOSE DE MARIQUINA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN JOSE DE MAIPO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN MIGUEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN PEDRO DE ATACAMA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN PEDRO DE LA PAZ',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN RAMON',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SAN VICENTE DE TAGUA TAGUA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTA BARBARA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTA CRUZ',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTA JUANA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTA MARIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTIAGO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'SANTO DOMINGO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TALCA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TALCAHUANO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TALTAL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TEMUCO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TENO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TIERRA AMARILLA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TILTIL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TOCOPILLA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TOME',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'TRAIGUEN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VALDIVIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VALLE GRANDE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VALLENAR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VALPARAISO',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VICTORIA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VICUÑA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VILCUN',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VILLA ALEGRE',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VILLA ALEMANA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VILLARICA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VIÑA DEL MAR',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'VITACURA',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'YUMBEL',1);
INSERT INTO CIUDAD VALUES(ID_CIUDAD.NEXTVAL,'YUNGAY',1);

INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'PUERTO MONNT',1);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ALGARROBO',2);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ALTO HOSPICIO',3);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'BUIN',4);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ANCUD',5);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ANDACOLLO',6);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ANGOL',7);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ANTOFAGASTA',8);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ARAUCO',9);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ARICA',10);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'LAMPA',11);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'MELIPILLA',12);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'BUIN',13);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'BULNES',14);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CABILDO',15);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CABRERO',16);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CALAMA',17);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CALBUCO',18);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CALDERA',19);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CALERA DE TANGO',20);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CALLE LARGA',21);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CAÑETE',22);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CARAHUE',23);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CARTAGENA',24);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CASABLANCA',25);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CASTRO',26);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CATEMU',27);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CAUQUENES',28);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CERRILLOS',29);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CERRO NAVIA',30);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHAITEN',31);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLINA',32);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHAÑARAL',33);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHEPICA',34);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLINA',35);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHIGUAYANTE',36);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHILE CHICO',37);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHILLAN',38);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHILLAN VIEJO',39);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHIMBARONGO',40);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CHONCHI',41);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'PUDAGUEL',42);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COCHRANE',43);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CODEGUA',44);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COELEMU',45);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COIHUECO',46);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLBUN',47);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLINA',48);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLLIPULLI',49);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COLTAUCO',50);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COMBARBALA',51);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CONCEPCION',52);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CONCHALI',53);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CONCON',54);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CONSTITUCION',55);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COPIAPO',56);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CORONEL',57);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'COYHAIQUE',58);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'MAULE',59);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CUNCO',60);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CURACAUTIN',61);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CURACAVI',62);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CURANILAHUE',63);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'CURICO',64);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'DALCAHUE',65);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'DIEGO DE ALMAGRO',66);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'DOÑIHUE',67);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'EL BOSQUE',68);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'NOGALES',69);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'EL MONTE',70);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'MONTE PATRIA',71);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'PIRQUE',72);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'EL QUISCO',73);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'DIEGO DE ALMAGRO',74);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'EL TABO',75);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ESTACION',76);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'FREIRE',77);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'FRESIA',78);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'FRUTILLAR',79);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'FUTRONO',80);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'GORBEA',81);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'GRANERO',82);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'OLIVAR',83);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ISLA DE PASCUA',84);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HIJUELAS',85);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HUALAÑE',86);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HUALPEN',87);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HUALQUI',88);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HUASCO',89);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'HUECHURABA',90);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'TUCAPEL',91);
INSERT INTO COMUNA VALUES (ID_COMUNA.NEXTVAL,'ILLAPEL',92);

INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ARICA','MIRAFLORES #456',1,10);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ARICA 2','EL TONGO #2465',1,10);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO PUERTO MONNT','MAHUZIER #150',3,1);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ALGARROBO','CANELO #815',2,2);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO BUIN','COIGUE #462',5,4);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ANDUD','PADRE HURTADO #3244',4,5);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ANDACOLLO','SIN NOMBRE $404',3,6);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ARAUCO','EL GUILLE #765',3,9);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO MELIPILLA','LA SILLA #7242',2,12);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO CALDERA','ALTO HORNO #625',2,19);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO CATEMU','EL CATEO #5534',3,27);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO CERRO NAVIA','CERRO #5442',5,30);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO CHIGUAYANTE','RIO CLARO #653',3,36);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO LEONERA','EL PITO 2 #1353',3,36);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO COLINA','CALLE 1 #4332',5,48);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ANTOFAGASTA','EL MICHELO #764',1,8);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ZALDIVAR','CALLE 3 #64',1,8);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO COELEMU','FRUTILLAR $54345',3,45);
INSERT INTO RECINTO VALUES(ID_RECINTO.NEXTVAL,'TNT LIT CARGO ILLAPEL','ANTOFATASTA #423',2,92);


INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'JUAN', 'CARLOS', 'GONZALEZ', 'PEREZ', TO_DATE('15-05-1985', 'DD-MM-YYYY'), 'Caducado', TO_DATE('10-01-2020', 'DD-MM-YYYY'), 'juan.gonzalez@tnt.com', 912345678, 1, 'MIRAFLORES #456', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'PEDRO', NULL, 'LOPEZ', 'SOTO', TO_DATE('22-08-1990', 'DD-MM-YYYY'), 'Activo', TO_DATE('15-03-2019', 'DD-MM-YYYY'), 'pedro.lopez@tnt.com', 987654321, 2, 'EL TONGO #2465', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MARIA', 'ISABEL', 'MARTINEZ', 'GARCIA', TO_DATE('03-11-1988', 'DD-MM-YYYY'), 'Caducado', TO_DATE('20-05-2021', 'DD-MM-YYYY'), 'maria.martinez@tnt.com', 945678123, 3, 'MAHUZIER #150', 1);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CARLOS', 'ANDRES', 'SILVA', 'ROJAS', TO_DATE('30-07-1992', 'DD-MM-YYYY'), 'Activo', TO_DATE('05-09-2018', 'DD-MM-YYYY'), 'carlos.silva@tnt.com', 932156487, 4, 'CANELO #815', 2);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ANA', 'LUISA', 'TORRES', 'MORALES', TO_DATE('12-04-1987', 'DD-MM-YYYY'), 'Caducado', TO_DATE('18-11-2020', 'DD-MM-YYYY'), 'ana.torres@tnt.com', 965432187, 5, 'COIGUE #462', 4);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'LUIS', 'MIGUEL', 'DIAZ', 'CASTILLO', TO_DATE('25-09-1991', 'DD-MM-YYYY'), 'Activo', TO_DATE('22-02-2019', 'DD-MM-YYYY'), 'luis.diaz@tnt.com', 978945612, 6, 'PADRE HURTADO #3244', 5);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'PATRICIA', NULL, 'RAMIREZ', 'VARGAS', TO_DATE('08-12-1989', 'DD-MM-YYYY'), 'Caducado', TO_DATE('14-07-2021', 'DD-MM-YYYY'), 'patricia.ramirez@tnt.com', 912348765, 7, 'SIN NOMBRE $404', 6);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ROBERTO', 'JAVIER', 'MORALES', 'FUENTES', TO_DATE('19-03-1986', 'DD-MM-YYYY'), 'Activo', TO_DATE('03-04-2018', 'DD-MM-YYYY'), 'roberto.morales@tnt.com', 956781234, 8, 'EL GUILLE #765', 9);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'SOFIA', 'ALEJANDRA', 'CASTRO', 'MENDOZA', TO_DATE('07-06-1993', 'DD-MM-YYYY'), 'Caducado', TO_DATE('28-10-2020', 'DD-MM-YYYY'), 'sofia.castro@tnt.com', 923456781, 9, 'LA SILLA #7242', 12);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'JORGE', 'ALBERTO', 'GUTIERREZ', 'SALAZAR', TO_DATE('14-01-1984', 'DD-MM-YYYY'), 'Activo', TO_DATE('09-12-2017', 'DD-MM-YYYY'), 'jorge.gutierrez@tnt.com', 967812345, 10, 'ALTO HORNO #625', 19);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CLAUDIA', 'PATRICIA', 'HERNANDEZ', 'ESPINOZA', TO_DATE('27-10-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('16-08-2021', 'DD-MM-YYYY'), 'claudia.hernandez@tnt.com', 934567812, 11, 'EL CATEO #5534', 27);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MARCELO', 'ANTONIO', 'FLORES', 'CORTES', TO_DATE('05-02-1988', 'DD-MM-YYYY'), 'Activo', TO_DATE('25-05-2019', 'DD-MM-YYYY'), 'marcelo.flores@tnt.com', 978123456, 12, 'CERRO #5442', 30);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'VALERIA', 'MACARENA', 'ROJAS', 'MUNOZ', TO_DATE('11-07-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('30-09-2020', 'DD-MM-YYYY'), 'valeria.rojas@tnt.com', 912345687, 13, 'RIO CLARO #653', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FERNANDO', 'IGNACIO', 'NAVARRO', 'ACUÑA', TO_DATE('23-04-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('12-11-2018', 'DD-MM-YYYY'), 'fernando.navarro@tnt.com', 945612378, 14, 'EL PITO 2 #1353', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CAMILA', 'ANDREA', 'ORTEGA', 'GUZMAN', TO_DATE('16-09-1991', 'DD-MM-YYYY'), 'Caducado', TO_DATE('07-03-2021', 'DD-MM-YYYY'), 'camila.ortega@tnt.com', 967845123, 15, 'CALLE 1 #4332', 48);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'DIEGO', 'ARMANDO', 'VEGA', 'CARMONA', TO_DATE('29-12-1987', 'DD-MM-YYYY'), 'Activo', TO_DATE('19-06-2019', 'DD-MM-YYYY'), 'diego.vega@tnt.com', 978456123, 16, 'EL MICHELO #764', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'PAULA', 'CAROLINA', 'MIRANDA', 'SANDOVAL', TO_DATE('04-05-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('22-01-2020', 'DD-MM-YYYY'), 'paula.miranda@tnt.com', 912378456, 17, 'CALLE 3 #64', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'RICARDO', 'ALONSO', 'CONTRERAS', 'LEIVA', TO_DATE('18-08-1986', 'DD-MM-YYYY'), 'Activo', TO_DATE('11-04-2018', 'DD-MM-YYYY'), 'ricardo.contreras@tnt.com', 945678231, 18, 'FRUTILLAR $54345', 45);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'NATALIA', 'SOLEDAD', 'FIGUEROA', 'TAPIA', TO_DATE('21-01-1993', 'DD-MM-YYYY'), 'Caducado', TO_DATE('05-12-2021', 'DD-MM-YYYY'), 'natalia.figueroa@tnt.com', 967812354, 19, 'ANTOFATASTA #423', 92);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MARTIN', 'GABRIEL', 'ARIAS', 'POBLETE', TO_DATE('09-03-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('17-07-2019', 'DD-MM-YYYY'), 'martin.arias@tnt.com', 978123645, 1, 'MIRAFLORES #456', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CAROLINA', NULL, 'CORTES', 'ZAMORA', TO_DATE('14-06-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('23-10-2020', 'DD-MM-YYYY'), 'carolina.cortes@tnt.com', 912345768, 2, 'EL TONGO #2465', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'SEBASTIAN', 'IGNACIO', 'VALENZUELA', 'CIFUENTES', TO_DATE('27-11-1987', 'DD-MM-YYYY'), 'Activo', TO_DATE('08-05-2019', 'DD-MM-YYYY'), 'sebastian.valenzuela@tnt.com', 945612387, 3, 'MAHUZIER #150', 1);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'DANIELA', 'FERNANDA', 'SOTO', 'CARRASCO', TO_DATE('03-04-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('19-02-2021', 'DD-MM-YYYY'), 'daniela.soto@tnt.com', 967845132, 4, 'CANELO #815', 2);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'HECTOR', 'MANUEL', 'PINO', 'LAGOS', TO_DATE('12-09-1985', 'DD-MM-YYYY'), 'Activo', TO_DATE('14-11-2018', 'DD-MM-YYYY'), 'hector.pino@tnt.com', 978456213, 5, 'COIGUE #462', 4);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'VERONICA', 'PAZ', 'GOMEZ', 'BRAVO', TO_DATE('25-02-1991', 'DD-MM-YYYY'), 'Caducado', TO_DATE('27-06-2020', 'DD-MM-YYYY'), 'veronica.gomez@tnt.com', 912378564, 6, 'PADRE HURTADO #3244', 5);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'RAUL', 'ESTEBAN', 'MALDONADO', 'PARRA', TO_DATE('08-07-1988', 'DD-MM-YYYY'), 'Activo', TO_DATE('03-03-2019', 'DD-MM-YYYY'), 'raul.maldonado@tnt.com', 945678312, 7, 'SIN NOMBRE $404', 6);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ISABEL', 'CRISTINA', 'JARA', 'VENEGAS', TO_DATE('19-10-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('16-09-2021', 'DD-MM-YYYY'), 'isabel.jara@tnt.com', 967812435, 8, 'EL GUILLE #765', 9);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'PABLO', 'ANDRES', 'SAAVEDRA', 'CACERES', TO_DATE('07-01-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('22-12-2018', 'DD-MM-YYYY'), 'pablo.saavedra@tnt.com', 978123546, 9, 'LA SILLA #7242', 12);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'KAREN', 'BELEN', 'TAPIA', 'SANHUEZA', TO_DATE('14-05-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('11-08-2020', 'DD-MM-YYYY'), 'karen.tapia@tnt.com', 912345876, 10, 'ALTO HORNO #625', 19);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FELIPE', 'ALEXIS', 'RIVAS', 'IBARRA', TO_DATE('27-08-1987', 'DD-MM-YYYY'), 'Activo', TO_DATE('05-04-2019', 'DD-MM-YYYY'), 'felipe.rivas@tnt.com', 945612738, 11, 'EL CATEO #5534', 27);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'LORENA', 'ANTONIETA', 'QUIROZ', 'MOLINA', TO_DATE('05-12-1991', 'DD-MM-YYYY'), 'Caducado', TO_DATE('18-01-2021', 'DD-MM-YYYY'), 'lorena.quiroz@tnt.com', 967845213, 12, 'CERRO #5442', 30);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'GONZALO', 'MARTIN', 'SALINAS', 'PIZARRO', TO_DATE('11-03-1988', 'DD-MM-YYYY'), 'Activo', TO_DATE('29-07-2019', 'DD-MM-YYYY'), 'gonzalo.salinas@tnt.com', 978123654, 13, 'RIO CLARO #653', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'YASNA', 'MILENA', 'CARDENAS', 'ALARCON', TO_DATE('23-06-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('14-10-2020', 'DD-MM-YYYY'), 'yasna.cardenas@tnt.com', 912378645, 14, 'EL PITO 2 #1353', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MAURICIO', 'JAVIER', 'POBLETE', 'ZAMBRANO', TO_DATE('16-11-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('07-05-2019', 'DD-MM-YYYY'), 'mauricio.poblete@tnt.com', 945678132, 15, 'CALLE 1 #4332', 48);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CONSTANZA', 'VALENTINA', 'LAGOS', 'ROJAS', TO_DATE('29-04-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('20-02-2021', 'DD-MM-YYYY'), 'constanza.lagos@tnt.com', 967812543, 16, 'EL MICHELO #764', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'VICTOR', 'HUGO', 'CAMPOS', 'SEPULVEDA', TO_DATE('04-09-1986', 'DD-MM-YYYY'), 'Activo', TO_DATE('12-11-2018', 'DD-MM-YYYY'), 'victor.campos@tnt.com', 978456132, 17, 'CALLE 3 #64', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'JAVIERA', 'IGNACIA', 'VALDES', 'TORO', TO_DATE('18-02-1991', 'DD-MM-YYYY'), 'Caducado', TO_DATE('25-08-2020', 'DD-MM-YYYY'), 'javier.valdes@tnt.com', 912345687, 18, 'FRUTILLAR $54345', 45);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CRISTIAN', 'ALEXIS', 'MUÑOZ', 'GARRIDO', TO_DATE('21-07-1988', 'DD-MM-YYYY'), 'Activo', TO_DATE('09-06-2019', 'DD-MM-YYYY'), 'cristian.munoz@tnt.com', 945612837, 19, 'ANTOFATASTA #423', 92);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FRANCISCA', 'JAVIERA', 'CASTRO', 'LOPEZ', TO_DATE('09-10-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('17-03-2021', 'DD-MM-YYYY'), 'francisca.castro@tnt.com', 967845321, 1, 'MIRAFLORES #456', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'IGNACIO', 'ALONSO', 'SANTANDER', 'MORALES', TO_DATE('14-01-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('23-12-2019', 'DD-MM-YYYY'), 'ignacio.santander@tnt.com', 978123465, 2, 'EL TONGO #2465', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'VALENTINA', 'ANTONIA', 'ARAYA', 'SILVA', TO_DATE('27-05-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('08-09-2020', 'DD-MM-YYYY'), 'valentina.araya@tnt.com', 912378546, 3, 'MAHUZIER #150', 1);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'RODRIGO', 'FELIPE', 'ESPINOZA', 'CACERES', TO_DATE('03-08-1987', 'DD-MM-YYYY'), 'Activo', TO_DATE('19-04-2019', 'DD-MM-YYYY'), 'rodrigo.espinoza@tnt.com', 945678213, 4, 'CANELO #815', 2);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'PAZ', 'ALEJANDRA', 'ROMERO', 'GONZALEZ', TO_DATE('12-12-1991', 'DD-MM-YYYY'), 'Caducado', TO_DATE('14-01-2021', 'DD-MM-YYYY'), 'paz.romero@tnt.com', 967812345, 5, 'COIGUE #462', 4);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ALVARO', 'MARTIN', 'TORRES', 'SOTO', TO_DATE('25-03-1988', 'DD-MM-YYYY'), 'Activo', TO_DATE('27-07-2019', 'DD-MM-YYYY'), 'alvaro.torres@tnt.com', 978456321, 6, 'PADRE HURTADO #3244', 5);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ANTONIA', 'BELEN', 'LEIVA', 'MUNOZ', TO_DATE('08-06-1992', 'DD-MM-YYYY'), 'Caducado', TO_DATE('03-10-2020', 'DD-MM-YYYY'), 'antonia.leiva@tnt.com', 912345786, 7, 'SIN NOMBRE $404', 6);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FABIAN', 'ESTEBAN', 'CARRASCO', 'FUENTES', TO_DATE('19-09-1989', 'DD-MM-YYYY'), 'Activo', TO_DATE('16-05-2019', 'DD-MM-YYYY'), 'fabian.carrasco@tnt.com', 945612387, 8, 'EL GUILLE #765', 9);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'DANIELA', 'CAROLINA', 'NAVARRO', 'PEREZ', TO_DATE('07-02-1990', 'DD-MM-YYYY'), 'Caducado', TO_DATE('22-11-2020', 'DD-MM-YYYY'), 'daniela.navarro@tnt.com', 967845123, 9, 'LA SILLA #7242', 12);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MATIAS', 'ALEXIS', 'RIQUELME', 'SALGADO', TO_DATE('14-07-1987', 'DD-MM-YYYY'), 'Activo', TO_DATE('11-08-2019', 'DD-MM-YYYY'), 'matias.riquelme@tnt.com', 978123456, 10, 'ALTO HORNO #625', 19);

INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ALEJANDRO', 'JAVIER', 'MENDOZA', 'CASTRO', TO_DATE('10-02-1993', 'DD-MM-YYYY'), 'Activo', TO_DATE('15-01-2024', 'DD-MM-YYYY'), 'alejandro.mendoza@tnt.com', 912345789, 1, 'LOS ALERCES #123', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'BRENDA', 'FERNANDA', 'SANCHEZ', 'GUTIERREZ', TO_DATE('05-08-1994', 'DD-MM-YYYY'), 'Activo', TO_DATE('20-03-2024', 'DD-MM-YYYY'), 'brenda.sanchez@tnt.com', 987654123, 2, 'LAS ACACIAS #456', 10);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'GABRIEL', NULL, 'VARGAS', 'MALDONADO', TO_DATE('12-11-1995', 'DD-MM-YYYY'), 'Activo', TO_DATE('10-05-2024', 'DD-MM-YYYY'), 'gabriel.vargas@tnt.com', 945678912, 3, 'LOS OLIVOS #789', 1);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MACARENA', 'ANTONIA', 'HERRERA', 'LAGOS', TO_DATE('25-04-1992', 'DD-MM-YYYY'), 'Activo', TO_DATE('05-07-2024', 'DD-MM-YYYY'), 'macarena.herrera@tnt.com', 932156789, 4, 'LOS PINOS #321', 2);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FELIPE', 'IGNACIO', 'ZAMORA', 'PIZARRO', TO_DATE('18-09-1993', 'DD-MM-YYYY'), 'Activo', TO_DATE('18-09-2024', 'DD-MM-YYYY'), 'felipe.zamora@tnt.com', 965432198, 5, 'LOS ROBLES #654', 4);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'VALERIA', 'PAZ', 'CONTRERAS', 'SEPULVEDA', TO_DATE('30-01-1994', 'DD-MM-YYYY'), 'Activo', TO_DATE('22-11-2024', 'DD-MM-YYYY'), 'valeria.contreras@tnt.com', 978945623, 6, 'LOS CEDROS #987', 5);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CRISTOBAL', 'ANDRES', 'TAPIA', 'JARA', TO_DATE('14-06-1991', 'DD-MM-YYYY'), 'Activo', TO_DATE('14-02-2024', 'DD-MM-YYYY'), 'cristobal.tapia@tnt.com', 912348976, 7, 'LOS ABETOS #159', 6);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'JAVIERA', 'ISIDORA', 'PARRA', 'CORTES', TO_DATE('22-03-1995', 'DD-MM-YYYY'), 'Activo', TO_DATE('03-04-2024', 'DD-MM-YYYY'), 'javier.parra@tnt.com', 956781345, 8, 'LOS CASTAÑOS #753', 9);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MARTIN', 'ALONSO', 'SOTO', 'MUNOZ', TO_DATE('07-10-1992', 'DD-MM-YYYY'), 'Activo', TO_DATE('28-06-2024', 'DD-MM-YYYY'), 'martin.soto@tnt.com', 923456798, 9, 'LOS CEREZOS #357', 12);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'CATALINA', 'BELEN', 'ROJAS', 'GONZALEZ', TO_DATE('19-05-1994', 'DD-MM-YYYY'), 'Activo', TO_DATE('09-08-2024', 'DD-MM-YYYY'), 'catalina.rojas@tnt.com', 967812456, 10, 'LOS LINGUES #852', 19);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'SEBASTIAN', 'PABLO', 'MOLINA', 'SILVA', TO_DATE('11-12-1993', 'DD-MM-YYYY'), 'Activo', TO_DATE('16-03-2024', 'DD-MM-YYYY'), 'sebastian.molina@tnt.com', 934567891, 11, 'LOS COIGUES #456', 27);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ANTONELLA', 'VALENTINA', 'FUENTES', 'DIAZ', TO_DATE('03-07-1995', 'DD-MM-YYYY'), 'Activo', TO_DATE('25-05-2024', 'DD-MM-YYYY'), 'antonella.fuentes@tnt.com', 978123567, 12, 'LOS CANELOS #789', 30);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'MAXIMILIANO', 'JOSE', 'CARMONA', 'LOPEZ', TO_DATE('15-02-1991', 'DD-MM-YYYY'), 'Activo', TO_DATE('30-09-2024', 'DD-MM-YYYY'), 'maximiliano.carmona@tnt.com', 912345678, 13, 'LOS QUILAYES #123', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'FLORENCIA', 'IGNACIA', 'SALGADO', 'MARTINEZ', TO_DATE('28-09-1994', 'DD-MM-YYYY'), 'Activo', TO_DATE('12-11-2024', 'DD-MM-YYYY'), 'florencia.salgado@tnt.com', 945612398, 14, 'LOS MAQUIS #456', 36);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'BENJAMIN', 'FELIPE', 'PEREZ', 'GARCIA', TO_DATE('09-04-1993', 'DD-MM-YYYY'), 'Activo', TO_DATE('07-01-2025', 'DD-MM-YYYY'), 'benjamin.perez@tnt.com', 967845234, 15, 'LOS BOLDOS #789', 48);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'AMANDA', 'JOSEFINA', 'GUTIERREZ', 'RAMIREZ', TO_DATE('21-11-1995', 'DD-MM-YYYY'), 'Activo', TO_DATE('19-02-2025', 'DD-MM-YYYY'), 'amanda.gutierrez@tnt.com', 978456234, 16, 'LOS LUMAS #123', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'JOAQUIN', 'MATEO', 'CORTES', 'TORRES', TO_DATE('04-06-1992', 'DD-MM-YYYY'), 'Activo', TO_DATE('22-04-2025', 'DD-MM-YYYY'), 'joaquin.cortes@tnt.com', 912378567, 17, 'LOS PEUMOS #456', 8);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'ISIDORA', 'ANTONIA', 'MUNOZ', 'HERNANDEZ', TO_DATE('17-01-1994', 'DD-MM-YYYY'), 'Activo', TO_DATE('11-06-2025', 'DD-MM-YYYY'), 'isidora.munoz@tnt.com', 945678342, 18, 'LOS RADALES #789', 45);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'TOMAS', 'AGUSTIN', 'GARRIDO', 'NAVARRO', TO_DATE('29-08-1993', 'DD-MM-YYYY'), 'Activo', TO_DATE('05-08-2025', 'DD-MM-YYYY'), 'tomas.garrido@tnt.com', 967812456, 19, 'LOS RAULIES #123', 92);
INSERT INTO GUARDIA VALUES (ID_GUARDIA.NEXTVAL, 'EMILIA', 'ROSARIO', 'LOPEZ', 'CASTILLO', TO_DATE('12-03-1995', 'DD-MM-YYYY'), 'Activo', TO_DATE('17-10-2025', 'DD-MM-YYYY'), 'emilia.lopez@tnt.com', 978123678, 1, 'LOS AVELINOS #456', 10);

INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/01/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/02/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/03/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/04/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/05/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/06/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('21/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('24/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('21/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('24/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('25/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('28/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('25/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('28/11/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('01/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('04/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('05/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('06/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('08/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('09/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('12/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('13/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('16/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('17/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('20/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('21/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('24/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('21/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('24/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('25/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('28/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'DIURNO',40000);
INSERT INTO TURNO VALUES(ID_TURNO.NEXTVAL,TO_DATE('25/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),TO_DATE('28/12/'||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)),'DD/MM/YYYY'),'VESPERTINO',45000);

INSERT INTO ASIGNAR VALUES (10, 1);
INSERT INTO ASIGNAR VALUES (30, 2);
INSERT INTO ASIGNAR VALUES (50, 3);
INSERT INTO ASIGNAR VALUES (70, 4);
INSERT INTO ASIGNAR VALUES (90, 5);
INSERT INTO ASIGNAR VALUES (110, 6);
INSERT INTO ASIGNAR VALUES (130, 7);
INSERT INTO ASIGNAR VALUES (150, 8);
INSERT INTO ASIGNAR VALUES (170, 9);
INSERT INTO ASIGNAR VALUES (190, 10);
INSERT INTO ASIGNAR VALUES (210, 11);
INSERT INTO ASIGNAR VALUES (230, 12);
INSERT INTO ASIGNAR VALUES (250, 13);
INSERT INTO ASIGNAR VALUES (270, 14);
INSERT INTO ASIGNAR VALUES (290, 15);
INSERT INTO ASIGNAR VALUES (310, 16);
INSERT INTO ASIGNAR VALUES (330, 17);
INSERT INTO ASIGNAR VALUES (350, 18);
INSERT INTO ASIGNAR VALUES (370, 19);
INSERT INTO ASIGNAR VALUES (390, 20);
INSERT INTO ASIGNAR VALUES (410, 21);
INSERT INTO ASIGNAR VALUES (430, 22);
INSERT INTO ASIGNAR VALUES (450, 23);
INSERT INTO ASIGNAR VALUES (470, 24);
INSERT INTO ASIGNAR VALUES (490, 25);
INSERT INTO ASIGNAR VALUES (510, 26);
INSERT INTO ASIGNAR VALUES (530, 27);
INSERT INTO ASIGNAR VALUES (550, 28);
INSERT INTO ASIGNAR VALUES (570, 29);
INSERT INTO ASIGNAR VALUES (590, 30);
INSERT INTO ASIGNAR VALUES (610, 31);
INSERT INTO ASIGNAR VALUES (630, 32);
INSERT INTO ASIGNAR VALUES (650, 33);
INSERT INTO ASIGNAR VALUES (670, 34);
INSERT INTO ASIGNAR VALUES (690, 35);
INSERT INTO ASIGNAR VALUES (710, 36);
INSERT INTO ASIGNAR VALUES (730, 37);
INSERT INTO ASIGNAR VALUES (750, 38);
INSERT INTO ASIGNAR VALUES (770, 39);
INSERT INTO ASIGNAR VALUES (790, 40);
INSERT INTO ASIGNAR VALUES (10, 41);
INSERT INTO ASIGNAR VALUES (30, 42);
INSERT INTO ASIGNAR VALUES (50, 43);
INSERT INTO ASIGNAR VALUES (70, 44);
INSERT INTO ASIGNAR VALUES (90, 45);
INSERT INTO ASIGNAR VALUES (110, 46);
INSERT INTO ASIGNAR VALUES (130, 47);
INSERT INTO ASIGNAR VALUES (150, 48);
INSERT INTO ASIGNAR VALUES (170, 49);
INSERT INTO ASIGNAR VALUES (190, 50);

INSERT INTO CONDUCTOR VALUES (12345678, 'K', 'JUAN', 'CARLOS', 'GONZALEZ', TO_DATE('15-05-1985', 'DD-MM-YYYY'), 'MIRAFLORES #456', 912345678, 10);
INSERT INTO CONDUCTOR VALUES (23456789, '1', 'PEDRO', NULL, 'LOPEZ', TO_DATE('22-08-1990', 'DD-MM-YYYY'), 'EL TONGO #2465', 987654321, 30);
INSERT INTO CONDUCTOR VALUES (34567890, '2', 'MARIA', 'ISABEL', 'MARTINEZ', TO_DATE('03-11-1988', 'DD-MM-YYYY'), 'MAHUZIER #150', 945678123, 50);
INSERT INTO CONDUCTOR VALUES (45678901, '3', 'CARLOS', 'ANDRES', 'SILVA', TO_DATE('30-07-1992', 'DD-MM-YYYY'), 'CANELO #815', 932156487, 70);
INSERT INTO CONDUCTOR VALUES (56789012, '4', 'ANA', 'LUISA', 'TORRES', TO_DATE('12-04-1987', 'DD-MM-YYYY'), 'COIGUE #462', 965432187, 90);
INSERT INTO CONDUCTOR VALUES (67890123, '5', 'LUIS', 'MIGUEL', 'DIAZ', TO_DATE('25-09-1991', 'DD-MM-YYYY'), 'PADRE HURTADO #3244', 978945612, 110);
INSERT INTO CONDUCTOR VALUES (78901234, '6', 'PATRICIA', NULL, 'RAMIREZ', TO_DATE('08-12-1989', 'DD-MM-YYYY'), 'SIN NOMBRE $404', 912348765, 130);
INSERT INTO CONDUCTOR VALUES (89012345, '7', 'ROBERTO', 'JAVIER', 'MORALES', TO_DATE('19-03-1986', 'DD-MM-YYYY'), 'EL GUILLE #765', 956781234, 150);
INSERT INTO CONDUCTOR VALUES (90123456, '8', 'SOFIA', 'ALEJANDRA', 'CASTRO', TO_DATE('07-06-1993', 'DD-MM-YYYY'), 'LA SILLA #7242', 923456781, 170);
INSERT INTO CONDUCTOR VALUES (11223344, '9', 'JORGE', 'ALBERTO', 'GUTIERREZ', TO_DATE('14-01-1984', 'DD-MM-YYYY'), 'ALTO HORNO #625', 967812345, 190);
INSERT INTO CONDUCTOR VALUES (22334455, '0', 'CLAUDIA', 'PATRICIA', 'HERNANDEZ', TO_DATE('27-10-1990', 'DD-MM-YYYY'), 'EL CATEO #5534', 934567812, 210);
INSERT INTO CONDUCTOR VALUES (33445566, '1', 'MARCELO', 'ANTONIO', 'FLORES', TO_DATE('05-02-1988', 'DD-MM-YYYY'), 'CERRO #5442', 978123456, 230);
INSERT INTO CONDUCTOR VALUES (44556677, '2', 'VALERIA', 'MACARENA', 'ROJAS', TO_DATE('11-07-1992', 'DD-MM-YYYY'), 'RIO CLARO #653', 912345687, 250);
INSERT INTO CONDUCTOR VALUES (55667788, '3', 'FERNANDO', 'IGNACIO', 'NAVARRO', TO_DATE('23-04-1989', 'DD-MM-YYYY'), 'EL PITO 2 #1353', 945612378, 270);
INSERT INTO CONDUCTOR VALUES (66778899, '4', 'CAMILA', 'ANDREA', 'ORTEGA', TO_DATE('16-09-1991', 'DD-MM-YYYY'), 'CALLE 1 #4332', 967845123, 290);
INSERT INTO CONDUCTOR VALUES (77889900, '5', 'DIEGO', 'ARMANDO', 'VEGA', TO_DATE('29-12-1987', 'DD-MM-YYYY'), 'EL MICHELO #764', 978456123, 310);
INSERT INTO CONDUCTOR VALUES (88990011, '6', 'PAULA', 'CAROLINA', 'MIRANDA', TO_DATE('04-05-1990', 'DD-MM-YYYY'), 'CALLE 3 #64', 912378456, 330);
INSERT INTO CONDUCTOR VALUES (99001122, '7', 'RICARDO', 'ALONSO', 'CONTRERAS', TO_DATE('18-08-1986', 'DD-MM-YYYY'), 'FRUTILLAR $54345', 945678231, 350);
INSERT INTO CONDUCTOR VALUES (10111213, '8', 'NATALIA', 'SOLEDAD', 'FIGUEROA', TO_DATE('21-01-1993', 'DD-MM-YYYY'), 'ANTOFATASTA #423', 967812354, 370);
INSERT INTO CONDUCTOR VALUES (12131415, '9', 'MARTIN', 'GABRIEL', 'ARIAS', TO_DATE('09-03-1989', 'DD-MM-YYYY'), 'MIRAFLORES #456', 978123645, 390);
INSERT INTO CONDUCTOR VALUES (13141516, '0', 'CAROLINA', NULL, 'CORTES', TO_DATE('14-06-1992', 'DD-MM-YYYY'), 'EL TONGO #2465', 912345768, 410);
INSERT INTO CONDUCTOR VALUES (14151617, '1', 'SEBASTIAN', 'IGNACIO', 'VALENZUELA', TO_DATE('27-11-1987', 'DD-MM-YYYY'), 'MAHUZIER #150', 945612387, 430);
INSERT INTO CONDUCTOR VALUES (15161718, '2', 'DANIELA', 'FERNANDA', 'SOTO', TO_DATE('03-04-1990', 'DD-MM-YYYY'), 'CANELO #815', 967845132, 450);
INSERT INTO CONDUCTOR VALUES (16171819, '3', 'HECTOR', 'MANUEL', 'PINO', TO_DATE('12-09-1985', 'DD-MM-YYYY'), 'COIGUE #462', 978456213, 470);
INSERT INTO CONDUCTOR VALUES (17181920, '4', 'VERONICA', 'PAZ', 'GOMEZ', TO_DATE('25-02-1991', 'DD-MM-YYYY'), 'PADRE HURTADO #3244', 912378564, 490);
INSERT INTO CONDUCTOR VALUES (18192021, '5', 'RAUL', 'ESTEBAN', 'MALDONADO', TO_DATE('08-07-1988', 'DD-MM-YYYY'), 'SIN NOMBRE $404', 945678312, 510);
INSERT INTO CONDUCTOR VALUES (19202122, '6', 'ISABEL', 'CRISTINA', 'JARA', TO_DATE('19-10-1992', 'DD-MM-YYYY'), 'EL GUILLE #765', 967812435, 530);
INSERT INTO CONDUCTOR VALUES (20212223, '7', 'PABLO', 'ANDRES', 'SAAVEDRA', TO_DATE('07-01-1989', 'DD-MM-YYYY'), 'LA SILLA #7242', 978123546, 550);
INSERT INTO CONDUCTOR VALUES (21222324, '8', 'KAREN', 'BELEN', 'TAPIA', TO_DATE('14-05-1990', 'DD-MM-YYYY'), 'ALTO HORNO #625', 912345876, 570);
INSERT INTO CONDUCTOR VALUES (22232425, '9', 'FELIPE', 'ALEXIS', 'RIVAS', TO_DATE('27-08-1987', 'DD-MM-YYYY'), 'EL CATEO #5534', 945612738, 590);
INSERT INTO CONDUCTOR VALUES (23242526, '0', 'LORENA', 'ANTONIETA', 'QUIROZ', TO_DATE('05-12-1991', 'DD-MM-YYYY'), 'CERRO #5442', 967845213, 610);
INSERT INTO CONDUCTOR VALUES (24252627, '1', 'GONZALO', 'MARTIN', 'SALINAS', TO_DATE('11-03-1988', 'DD-MM-YYYY'), 'RIO CLARO #653', 978123654, 630);
INSERT INTO CONDUCTOR VALUES (25262728, '2', 'YASNA', 'MILENA', 'CARDENAS', TO_DATE('23-06-1992', 'DD-MM-YYYY'), 'EL PITO 2 #1353', 912378645, 650);
INSERT INTO CONDUCTOR VALUES (26272829, '3', 'MAURICIO', 'JAVIER', 'POBLETE', TO_DATE('16-11-1989', 'DD-MM-YYYY'), 'CALLE 1 #4332', 945678132, 670);
INSERT INTO CONDUCTOR VALUES (27282930, '4', 'CONSTANZA', 'VALENTINA', 'LAGOS', TO_DATE('29-04-1990', 'DD-MM-YYYY'), 'EL MICHELO #764', 967812543, 690);
INSERT INTO CONDUCTOR VALUES (28293031, '5', 'VICTOR', 'HUGO', 'CAMPOS', TO_DATE('04-09-1986', 'DD-MM-YYYY'), 'CALLE 3 #64', 978456132, 710);
INSERT INTO CONDUCTOR VALUES (29303132, '6', 'JAVIERA', 'IGNACIA', 'VALDES', TO_DATE('18-02-1991', 'DD-MM-YYYY'), 'FRUTILLAR $54345', 912345687, 730);
INSERT INTO CONDUCTOR VALUES (30313233, '7', 'CRISTIAN', 'ALEXIS', 'MUÑOZ', TO_DATE('21-07-1988', 'DD-MM-YYYY'), 'ANTOFATASTA #423', 945612837, 750);
INSERT INTO CONDUCTOR VALUES (31323334, '8', 'FRANCISCA', 'JAVIERA', 'CASTRO', TO_DATE('09-10-1992', 'DD-MM-YYYY'), 'MIRAFLORES #456', 967845321, 770);
INSERT INTO CONDUCTOR VALUES (32333435, '9', 'IGNACIO', 'ALONSO', 'SANTANDER', TO_DATE('14-01-1989', 'DD-MM-YYYY'), 'EL TONGO #2465', 978123465, 790);
INSERT INTO CONDUCTOR VALUES (33343536, '0', 'VALENTINA', 'ANTONIA', 'ARAYA', TO_DATE('27-05-1990', 'DD-MM-YYYY'), 'MAHUZIER #150', 912378546, 810);
INSERT INTO CONDUCTOR VALUES (34353637, '1', 'RODRIGO', 'FELIPE', 'ESPINOZA', TO_DATE('03-08-1987', 'DD-MM-YYYY'), 'CANELO #815', 945678213, 830);
INSERT INTO CONDUCTOR VALUES (35363738, '2', 'PAZ', 'ALEJANDRA', 'ROMERO', TO_DATE('12-12-1991', 'DD-MM-YYYY'), 'COIGUE #462', 967812345, 850);
INSERT INTO CONDUCTOR VALUES (36373839, '3', 'ALVARO', 'MARTIN', 'TORRES', TO_DATE('25-03-1988', 'DD-MM-YYYY'), 'PADRE HURTADO #3244', 978456321, 870);
INSERT INTO CONDUCTOR VALUES (37383940, '4', 'ANTONIA', 'BELEN', 'LEIVA', TO_DATE('08-06-1992', 'DD-MM-YYYY'), 'SIN NOMBRE $404', 912345786, 890);
INSERT INTO CONDUCTOR VALUES (38394041, '5', 'FABIAN', 'ESTEBAN', 'CARRASCO', TO_DATE('19-09-1989', 'DD-MM-YYYY'), 'EL GUILLE #765', 945612387, 910);
INSERT INTO CONDUCTOR VALUES (39404142, '6', 'DANIELA', 'CAROLINA', 'NAVARRO', TO_DATE('07-02-1990', 'DD-MM-YYYY'), 'LA SILLA #7242', 967845123, 930);
INSERT INTO CONDUCTOR VALUES (40414243, '7', 'MATIAS', 'ALEXIS', 'RIQUELME', TO_DATE('14-07-1987', 'DD-MM-YYYY'), 'ALTO HORNO #625', 978123456, 950);

INSERT INTO CAMION VALUES ('AB1234', 'Volvo', 'FH16', 3, 'Transportes Andes', 10, 12345678);
INSERT INTO CAMION VALUES ('CD2345', 'Scania', 'R500', 3, 'Cargo Express', 30, 23456789);
INSERT INTO CAMION VALUES ('EF3456', 'Mercedes-Benz', 'Actros', 2, 'Logística Sur', 50, 34567890);
INSERT INTO CAMION VALUES ('GH4567', 'MAN', 'TGX', 3, 'Transportes del Pacífico', 70, 45678901);
INSERT INTO CAMION VALUES ('IJ5678', 'Iveco', 'Stralis', 2, 'Cargo Norte', 90, 56789012);
INSERT INTO CAMION VALUES ('KL6789', 'Kenworth', 'T680', 3, 'Transportes Central', 110, 67890123);
INSERT INTO CAMION VALUES ('MN7890', 'Freightliner', 'Cascadia', 2, 'Logística Nacional', 130, 78901234);
INSERT INTO CAMION VALUES ('OP8901', 'DAF', 'XF', 3, 'Transportes Rápido', 150, 89012345);
INSERT INTO CAMION VALUES ('QR9012', 'Peterbilt', '579', 2, 'Cargo Sur', 170, 90123456);
INSERT INTO CAMION VALUES ('ST0123', 'Volvo', 'VNL', 3, 'Transportes Unión', 190, 11223344);
INSERT INTO CAMION VALUES ('UV1234', 'Scania', 'G450', 2, 'Logística Integrada', 210, 22334455);
INSERT INTO CAMION VALUES ('WX2345', 'Mercedes-Benz', 'Arocs', 3, 'Transportes Veloz', 230, 33445566);
INSERT INTO CAMION VALUES ('YZ3456', 'MAN', 'TGS', 2, 'Cargo Express', 250, 44556677);
INSERT INTO CAMION VALUES ('AA4567', 'Iveco', 'S-Way', 3, 'Transportes Andes', 270, 55667788);
INSERT INTO CAMION VALUES ('BB5678', 'Kenworth', 'W990', 2, 'Logística Sur', 290, 66778899);
INSERT INTO CAMION VALUES ('CC6789', 'Freightliner', 'M2', 3, 'Transportes del Pacífico', 310, 77889900);
INSERT INTO CAMION VALUES ('DD7890', 'DAF', 'CF', 2, 'Cargo Norte', 330, 88990011);
INSERT INTO CAMION VALUES ('EE8901', 'Peterbilt', '389', 3, 'Transportes Central', 350, 99001122);
INSERT INTO CAMION VALUES ('FF9012', 'Volvo', 'VHD', 2, 'Logística Nacional', 370, 10111213);
INSERT INTO CAMION VALUES ('GG0123', 'Scania', 'S730', 3, 'Transportes Rápido', 390, 12131415);
INSERT INTO CAMION VALUES ('HH1234', 'Mercedes-Benz', 'Antos', 2, 'Cargo Sur', 410, 13141516);
INSERT INTO CAMION VALUES ('II2345', 'MAN', 'TGM', 3, 'Transportes Unión', 430, 14151617);
INSERT INTO CAMION VALUES ('JJ3456', 'Iveco', 'Trakker', 2, 'Logística Integrada', 450, 15161718);
INSERT INTO CAMION VALUES ('KK4567', 'Kenworth', 'T880', 3, 'Transportes Veloz', 470, 16171819);
INSERT INTO CAMION VALUES ('LL5678', 'Freightliner', '108SD', 2, 'Cargo Express', 490, 17181920);
INSERT INTO CAMION VALUES ('MM6789', 'DAF', 'LF', 3, 'Transportes Andes', 510, 18192021);
INSERT INTO CAMION VALUES ('NN7890', 'Peterbilt', '567', 2, 'Logística Sur', 530, 19202122);
INSERT INTO CAMION VALUES ('OO8901', 'Volvo', 'FE', 3, 'Transportes del Pacífico', 550, 20212223);
INSERT INTO CAMION VALUES ('PP9012', 'Scania', 'P410', 2, 'Cargo Norte', 570, 21222324);
INSERT INTO CAMION VALUES ('QQ0123', 'Mercedes-Benz', 'Econic', 3, 'Transportes Central', 590, 22232425);
INSERT INTO CAMION VALUES ('RR1234', 'MAN', 'TGL', 2, 'Logística Nacional', 610, 23242526);
INSERT INTO CAMION VALUES ('SS2345', 'Iveco', 'Daily', 3, 'Transportes Rápido', 630, 24252627);
INSERT INTO CAMION VALUES ('TT3456', 'Kenworth', 'K370', 2, 'Cargo Sur', 650, 25262728);
INSERT INTO CAMION VALUES ('UU4567', 'Freightliner', '114SD', 3, 'Transportes Unión', 670, 26272829);
INSERT INTO CAMION VALUES ('VV5678', 'DAF', 'XG+', 2, 'Logística Integrada', 690, 27282930);
INSERT INTO CAMION VALUES ('WW6789', 'Peterbilt', '520', 3, 'Transportes Veloz', 710, 28293031);
INSERT INTO CAMION VALUES ('XX7890', 'Volvo', 'FMX', 2, 'Cargo Express', 730, 29303132);
INSERT INTO CAMION VALUES ('YY8901', 'Scania', 'L320', 3, 'Transportes Andes', 750, 30313233);
INSERT INTO CAMION VALUES ('ZZ9012', 'Mercedes-Benz', 'Unimog', 2, 'Logística Sur', 770, 31323334);
INSERT INTO CAMION VALUES ('A1B2C3', 'MAN', 'TGE', 3, 'Transportes del Pacífico', 790, 32333435);
INSERT INTO CAMION VALUES ('B2C3D4', 'Iveco', 'Eurocargo', 2, 'Cargo Norte', 810, 33343536);
INSERT INTO CAMION VALUES ('C3D4E5', 'Kenworth', 'T170', 3, 'Transportes Central', 830, 34353637);
INSERT INTO CAMION VALUES ('D4E5F6', 'Freightliner', 'Business Class', 2, 'Logística Nacional', 850, 35363738);
INSERT INTO CAMION VALUES ('E5F6G7', 'DAF', 'XG', 3, 'Transportes Rápido', 870, 36373839);
INSERT INTO CAMION VALUES ('F6G7H8', 'Peterbilt', '337', 2, 'Cargo Sur', 890, 37383940);
INSERT INTO CAMION VALUES ('G7H8I9', 'Volvo', 'FL', 3, 'Transportes Unión', 910, 38394041);
INSERT INTO CAMION VALUES ('H8I9J0', 'Scania', 'CR19', 2, 'Logística Integrada', 930, 39404142);
INSERT INTO CAMION VALUES ('I9J0K1', 'Mercedes-Benz', 'Zetros', 3, 'Transportes Veloz', 950, 40414243);

INSERT INTO TRACTO_CAMION VALUES ('TR1234', 'Volvo', 'FH16', 2, 'AB1234');
INSERT INTO TRACTO_CAMION VALUES ('TR2345', 'Scania', 'R500', 2, 'CD2345');
INSERT INTO TRACTO_CAMION VALUES ('TR3456', 'Mercedes-Benz', 'Actros', 2, 'EF3456');
INSERT INTO TRACTO_CAMION VALUES ('TR4567', 'MAN', 'TGX', 2, 'GH4567');
INSERT INTO TRACTO_CAMION VALUES ('TR5678', 'Iveco', 'Stralis', 2, 'IJ5678');
INSERT INTO TRACTO_CAMION VALUES ('TR6789', 'Kenworth', 'T680', 2, 'KL6789');
INSERT INTO TRACTO_CAMION VALUES ('TR7890', 'Freightliner', 'Cascadia', 2, 'MN7890');
INSERT INTO TRACTO_CAMION VALUES ('TR8901', 'DAF', 'XF', 2, 'OP8901');
INSERT INTO TRACTO_CAMION VALUES ('TR9012', 'Peterbilt', '579', 2, 'QR9012');
INSERT INTO TRACTO_CAMION VALUES ('TR0123', 'Volvo', 'VNL', 2, 'ST0123');
INSERT INTO TRACTO_CAMION VALUES ('TR1123', 'Scania', 'G450', 2, 'UV1234');
INSERT INTO TRACTO_CAMION VALUES ('TR2234', 'Mercedes-Benz', 'Arocs', 2, 'WX2345');
INSERT INTO TRACTO_CAMION VALUES ('TR3345', 'MAN', 'TGS', 2, 'YZ3456');
INSERT INTO TRACTO_CAMION VALUES ('TR4456', 'Iveco', 'S-Way', 2, 'AA4567');
INSERT INTO TRACTO_CAMION VALUES ('TR5567', 'Kenworth', 'W990', 2, 'BB5678');
INSERT INTO TRACTO_CAMION VALUES ('TR6678', 'Freightliner', 'M2', 2, 'CC6789');
INSERT INTO TRACTO_CAMION VALUES ('TR7789', 'DAF', 'CF', 2, 'DD7890');
INSERT INTO TRACTO_CAMION VALUES ('TR8890', 'Peterbilt', '389', 2, 'EE8901');
INSERT INTO TRACTO_CAMION VALUES ('TR9901', 'Volvo', 'VHD', 2, 'FF9012');
INSERT INTO TRACTO_CAMION VALUES ('TR0012', 'Scania', 'S730', 2, 'GG0123');
INSERT INTO TRACTO_CAMION VALUES ('TR1012', 'Mercedes-Benz', 'Antos', 2, 'HH1234');
INSERT INTO TRACTO_CAMION VALUES ('TR2023', 'MAN', 'TGM', 2, 'II2345');
INSERT INTO TRACTO_CAMION VALUES ('TR3034', 'Iveco', 'Trakker', 2, 'JJ3456');
INSERT INTO TRACTO_CAMION VALUES ('TR4045', 'Kenworth', 'T880', 2, 'KK4567');
INSERT INTO TRACTO_CAMION VALUES ('TR5056', 'Freightliner', '108SD', 2, 'LL5678');
INSERT INTO TRACTO_CAMION VALUES ('TR6067', 'DAF', 'LF', 2, 'MM6789');
INSERT INTO TRACTO_CAMION VALUES ('TR7078', 'Peterbilt', '567', 2, 'NN7890');
INSERT INTO TRACTO_CAMION VALUES ('TR8089', 'Volvo', 'FE', 2, 'OO8901');
INSERT INTO TRACTO_CAMION VALUES ('TR9090', 'Scania', 'P410', 2, 'PP9012');
INSERT INTO TRACTO_CAMION VALUES ('TR0101', 'Mercedes-Benz', 'Econic', 2, 'QQ0123');
INSERT INTO TRACTO_CAMION VALUES ('TR1112', 'MAN', 'TGL', 2, 'RR1234');
INSERT INTO TRACTO_CAMION VALUES ('TR2123', 'Iveco', 'Daily', 2, 'SS2345');
INSERT INTO TRACTO_CAMION VALUES ('TR3134', 'Kenworth', 'K370', 2, 'TT3456');
INSERT INTO TRACTO_CAMION VALUES ('TR4145', 'Freightliner', '114SD', 2, 'UU4567');
INSERT INTO TRACTO_CAMION VALUES ('TR5156', 'DAF', 'XG+', 2, 'VV5678');
INSERT INTO TRACTO_CAMION VALUES ('TR6167', 'Peterbilt', '520', 2, 'WW6789');
INSERT INTO TRACTO_CAMION VALUES ('TR7178', 'Volvo', 'FMX', 2, 'XX7890');
INSERT INTO TRACTO_CAMION VALUES ('TR8189', 'Scania', 'L320', 2, 'YY8901');
INSERT INTO TRACTO_CAMION VALUES ('TR9190', 'Mercedes-Benz', 'Unimog', 2, 'ZZ9012');
INSERT INTO TRACTO_CAMION VALUES ('TR0202', 'MAN', 'TGE', 2, 'A1B2C3');
INSERT INTO TRACTO_CAMION VALUES ('TR1213', 'Iveco', 'Eurocargo', 2, 'B2C3D4');
INSERT INTO TRACTO_CAMION VALUES ('TR2224', 'Kenworth', 'T170', 2, 'C3D4E5');
INSERT INTO TRACTO_CAMION VALUES ('TR3235', 'Freightliner', 'Business Class', 2, 'D4E5F6');
INSERT INTO TRACTO_CAMION VALUES ('TR4246', 'DAF', 'XG', 2, 'E5F6G7');
INSERT INTO TRACTO_CAMION VALUES ('TR5257', 'Peterbilt', '337', 2, 'F6G7H8');
INSERT INTO TRACTO_CAMION VALUES ('TR6268', 'Volvo', 'FL', 2, 'G7H8I9');
INSERT INTO TRACTO_CAMION VALUES ('TR7279', 'Scania', 'CR19', 2, 'H8I9J0');
INSERT INTO TRACTO_CAMION VALUES ('TR8280', 'Mercedes-Benz', 'Zetros', 2, 'I9J0K1');
INSERT INTO TRACTO_CAMION VALUES ('TR9291', 'Volvo', 'FM', 2, 'AB1234');
INSERT INTO TRACTO_CAMION VALUES ('TR0303', 'Scania', 'R450', 2, 'CD2345');
INSERT INTO TRACTO_CAMION VALUES ('TR1314', 'Mercedes-Benz', 'Axor', 2, 'EF3456');
INSERT INTO TRACTO_CAMION VALUES ('TR2325', 'MAN', 'F2000', 2, 'GH4567');
INSERT INTO TRACTO_CAMION VALUES ('TR3336', 'Iveco', 'EuroTech', 2, 'IJ5678');
INSERT INTO TRACTO_CAMION VALUES ('TR4347', 'Kenworth', 'T600', 2, 'KL6789');

COMMIT;